[package]
name = "safex-mine-helper"
version = "0.1.0"
description = "Elevated Windows mining helper for The Safex Mine"
authors = ["aussiesloth"]
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
] }

tokio = { version = "1", features = [
    "io-util",
    "net",
    "process",
    "rt-multi-thread",
    "macros",
    "time",
] }

[build-dependencies]
winresource = "0.1.31"